mode: "delivery" # or "emergency"
total_timesteps: 100000
eval_freq: 5000
learning_rate: 0.0003
buffer_size: 100000
batch_size: 128
gamma: 0.99
exploration_fraction: 0.3
exploration_initial_eps: 1.0
exploration_final_eps: 0.05
